# Generated by Django 3.2.1 on 2021-06-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0005_alter_vegpro_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='qunatity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
