# Generated by Django 3.2.1 on 2021-06-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0006_auto_20210610_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='prod',
            field=models.IntegerField(null=True),
        ),
    ]
