# Generated by Django 3.2.1 on 2021-06-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0007_myorders_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null='True')),
                ('prod', models.IntegerField(null=True)),
            ],
        ),
    ]
