# Generated by Django 3.2.1 on 2021-06-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_type',
            field=models.CharField(default='aa', max_length=300),
        ),
    ]
